# coding=utf-8
from random import randint

quotes = [
'Life is about making an impact, not making an income. –Kevin Kruse',
'Whatever the mind of man can conceive and believe, it can achieve. –Napoleon Hill',
'Strive not to be a success, but rather to be of value. –Albert Einstein',
'Two roads diverged in a wood, and I—I took the one less traveled by, And that has made all the difference.  –Robert Frost',
'I attribute my success to this: I never gave or took any excuse. –Florence Nightingale',
'You miss 100% of the shots you don’t take. –Wayne Gretzky',
'I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed. –Michael Jordan',
'The most difficult thing is the decision to act, the rest is merely tenacity. –Amelia Earhart',
'Every strike brings me closer to the next home run. –Babe Ruth',
'Definiteness of purpose is the starting point of all achievement. –W. Clement Stone',
'Life isn’t about getting and having, it’s about giving and being. –Kevin Kruse',
'Life is what happens to you while you’re busy making other plans. –John Lennon',
'We become what we think about. –Earl Nightingale',
'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do, so throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails.  Explore, Dream, Discover. –Mark Twain',
'Life is 10% what happens to me and 90% of how I react to it. –Charles Swindoll',
'The most common way people give up their power is by thinking they don’t have any. –Alice Walker',
'The mind is everything. What you think you become.  –Buddha',
'The best time to plant a tree was 20 years ago. The second best time is now. –Chinese Proverb',
'An unexamined life is not worth living. –Socrates',
'Eighty percent of success is showing up. –Woody Allen',
'Your time is limited, so don’t waste it living someone else’s life. –Steve Jobs',
'Winning isn’t everything, but wanting to win is. –Vince Lombardi',
'I am not a product of my circumstances. I am a product of my decisions. –Stephen Covey',
'Every child is an artist.  The problem is how to remain an artist once he grows up. –Pablo Picasso',
'You can never cross the ocean until you have the courage to lose sight of the shore. –Christopher Columbus',
'I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. –Maya Angelou',
'Either you run the day, or the day runs you. –Jim Rohn',
'Whether you think you can or you think you can’t, you’re right. –Henry Ford',
'The two most important days in your life are the day you are born and the day you find out why. –Mark Twain',
'Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it. –Johann Wolfgang von Goethe',
'The best revenge is massive success. –Frank Sinatra',
'People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily. –Zig Ziglar',
'Life shrinks or expands in proportion to one’s courage. –Anais Nin',
'If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced. –Vincent Van Gogh',
'There is only one way to avoid criticism: do nothing, say nothing, and be nothing. –Aristotle',
'Ask and it will be given to you; search, and you will find; knock and the door will be opened for you. –Jesus',
'The only person you are destined to become is the person you decide to be. –Ralph Waldo Emerson',
'Go confidently in the direction of your dreams.  Live the life you have imagined. –Henry David Thoreau',
'When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me. –Erma Bombeck',
'Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.  –Booker T. Washington',
'Certain things catch your eye, but pursue only those that capture the heart. – Ancient Indian Proverb',
'Believe you can and you’re halfway there. –Theodore Roosevelt',
'Everything you’ve ever wanted is on the other side of fear. –George Addair',
'We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. –Plato',
'Teach thy tongue to say, “I do not know,” and thous shalt progress. –Maimonides',
'Start where you are. Use what you have.  Do what you can. –Arthur Ashe',
'When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life. –John Lennon',
'Fall seven times and stand up eight. –Japanese Proverb',
'When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us. –Helen Keller',
'Everything has beauty, but not everyone can see. –Confucius',
'How wonderful it is that nobody need wait a single moment before starting to improve the world. –Anne Frank',
'When I let go of what I am, I become what I might be. –Lao Tzu',
'Life is not measured by the number of breaths we take, but by the moments that take our breath away. –Maya Angelou',
'Happiness is not something readymade.  It comes from your own actions. –Dalai Lama',
'If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on. –Sheryl Sandberg',
'First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end. –Aristotle',
'If the wind will not serve, take to the oars. –Latin Proverb',
'You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground. –Unknown',
'We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained. –Marie Curie',
'Too many of us are not living our dreams because we are living our fears. –Les Brown',
'Challenges are what make life interesting and overcoming them is what makes life meaningful. –Joshua J. Marine',
'If you want to lift yourself up, lift up someone else. –Booker T. Washington',
'I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. –Leonardo da Vinci',
'Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless. –Jamie Paolinetti',
'You take your life in your own hands, and what happens? A terrible thing, no one to blame. –Erica Jong',
'What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. –Bob Dylan',
'I didn’t fail the test. I just found 100 ways to do it wrong. –Benjamin Franklin',
'In order to succeed, your desire for success should be greater than your fear of failure. –Bill Cosby',
'A person who never made a mistake never tried anything new. – Albert Einstein',
'The person who says it cannot be done should not interrupt the person who is doing it. –Chinese Proverb',
'There are no traffic jams along the extra mile. –Roger Staubach',
'It is never too late to be what you might have been. –George Eliot',
'You become what you believe. –Oprah Winfrey',
'I would rather die of passion than of boredom. –Vincent van Gogh',
'A truly rich man is one whose children run into his arms when his hands are empty. –Unknown',
'It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.  –Ann Landers',
'If you want your children to turn out well, spend twice as much time with them, and half as much money. –Abigail Van Buren',
'Build your own dreams, or someone else will hire you to build theirs. –Farrah Gray',
'The battles that count aren’t the ones for gold medals. The struggles within yourself–the invisible battles inside all of us–that’s where it’s at. –Jesse Owens',
'Education costs money.  But then so does ignorance. –Sir Claus Moser',
'I have learned over the years that when one’s mind is made up, this diminishes fear. –Rosa Parks',
'It does not matter how slowly you go as long as you do not stop. –Confucius',
'If you look at what you have in life, you’ll always have more. If you look at what you don’t have in life, you’ll never have enough. –Oprah Winfrey',
'Remember that not getting what you want is sometimes a wonderful stroke of luck. –Dalai Lama',
'You can’t use up creativity.  The more you use, the more you have. –Maya Angelou',
'Dream big and dare to fail. –Norman Vaughan',
'Our lives begin to end the day we become silent about things that matter. –Martin Luther King Jr.',
'Do what you can, where you are, with what you have. –Teddy Roosevelt',
'If you do what you’ve always done, you’ll get what you’ve always gotten. –Tony Robbins',
'Dreaming, after all, is a form of planning. –Gloria Steinem',
'It’s your place in the world; it’s your life. Go on and do all you can with it, and make it the life you want to live. –Mae Jemison',
'You may be disappointed if you fail, but you are doomed if you don’t try. –Beverly Sills',
'Remember no one can make you feel inferior without your consent. –Eleanor Roosevelt',
'Life is what we make it, always has been, always will be. –Grandma Moses',
'The question isn’t who is going to let me; it’s who is going to stop me. –Ayn Rand',
'When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. –Henry Ford',
'It’s not the years in your life that count. It’s the life in your years. –Abraham Lincoln',
'Change your thoughts and you change your world. –Norman Vincent Peale',
'Either write something worth reading or do something worth writing. –Benjamin Franklin',
'Nothing is impossible, the word itself says, “I’m possible!” –Audrey Hepburn',
'The only way to do great work is to love what you do. –Steve Jobs',
'If you can dream it, you can achieve it. –Zig Ziglar',
'We are what we repeatedly do. Excellence, therefore, is not an act but a habit.  – Aristotle',
'The best way out is always through.  – Robert Frost',
'Do not wait to strike till the iron is hot; but make it hot by striking.  – William B. Sprague',
'Great spirits have always encountered violent opposition from mediocre minds.  – Albert Einstein',
'Whether you think you can or think you can’t, you’re right.  – Henry Ford',
'I know for sure that what we dwell on is who we become.  – Oprah Winfrey',
'I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times, I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.  – Michael Jordan',
'You must be the change you want to see in the world.  – Mahatma Gandhi',
'What you get by achieving your goals is not as important as what you become by achieving your goals.  – Goethe',
'You can get everything in life you want if you will just help enough other people get what they want.  – Zig Ziglar',
'Whatever you do will be insignificant, but it is very important that you do it.  – Mahatma Gandhi',
'Desire is the starting point of all achievement, not a hope, not a wish, but a keen pulsating desire which transcends everything.  – Napoleon Hill',
'Failure is the condiment that gives success its flavor.  – Truman Capote',
'Vision without action is daydream. Action without vision is nightmare.  – Japanese Proverb',
'In any situation, the best thing you can do is the right thing; the next best thing you can do is the wrong thing; the worst thing you can do is nothing.  – Theodore Roosevelt',
'If you keep saying things are going to be bad, you have a chance of being a prophet.  – Isaac B. Singer',
'Success consists of doing the common things of life uncommonly well.  – Unknown',
'Keep on going and the chances are you will stumble on something, perhaps when you are least expecting it. I have never heard of anyone stumbling on something sitting down.  – Charles F. Kettering, Engineer and Inventor',
'Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.  – Mark Twain',
'Losers visualize the penalties of failure. Winners visualize the rewards of success.  – Unknown',
'Some succeed because they are destined. Some succeed because they are determined.  – Unknown',
'Experience is what you get when you don’t get what you want.  – Dan Stanford',
'Setting an example is not the main means of influencing others; it is the only means.  – Albert Einstein',
'A happy person is not a person in a certain set of circumstances, but rather a person with a certain set of attitudes.  – Hugh Downs',
'If you’re going to be able to look back on something and laugh about it, you might as well laugh about it now.  – Marie Osmond',
'Remember that happiness is a way of travel, not a destination.  – Roy Goodman',
'If you want to test your memory, try to recall what you were worrying about one year ago today.  – E. Joseph Cossman',
'What lies behind us and what lies before us are tiny matters compared to what lies within us.  – Ralph Waldo Emerson',
'We judge of man’s wisdom by his hope.  – Ralph Waldo Emerson',
'The best way to cheer yourself up is to try to cheer somebody else up.  – Mark Twain',
'Age is an issue of mind over matter. If you don’t mind, it doesn’t matter.  – Mark Twain',
'Whenever you find yourself on the side of the majority, it’s time to pause and reflect.  – Mark Twain',
'Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.  – Mark Twain',
'The surest way not to fail is to determine to succeed.  – Richard B. Sheridan',
'Take the first step in faith. You don’t have to see the whole staircase, just take the first step.” – Dr. Martin Luther King Jr.',
'“Act or accept.” – Anonymous',
'Many great ideas go unexecuted, and many great executioners are without ideas. One without the other is worthless.  – Tim Blixseth',
'The world is more malleable than you think and it’s waiting for you to hammer it into shape.  – Bono',
'Sometimes you just got to give yourself what you wish someone else would give you.  – Dr Phil',
'Motivation is a fire from within. If someone else tries to light that fire under you, chances are it will burn very briefly.  – Stephen R. Covey',
'People become really quite remarkable when they start thinking that they can do things. When they believe in themselves they have the first secret of success.  – Norman Vincent Peale',
'Whenever you find whole world against you just turn around and lead the world.  – Anonymous',
'Being defeated is only a temporary condition; giving up is what makes it permanent.  – Marilyn vos Savant, Author and Advice Columnist',
'I can’t understand why people are frightened by new ideas. I’m frightened by old ones.  – John Cage',
'Fall down seven times, get up eight.  -Â Japanese Proverb',
'The difference between ordinary and extraordinary is that little extra.  – Unknown',
'The best way to predict the future is to create it.  – Unknown',
'Anyone can do something when they WANT to do it. Really successful people do things when they don’t want to do it.  – Dr. Phil',
'There are two primary choices in life: to accept conditions as they exist, or accept the responsibility for changing them.  – Dr. Denis Waitley',
'Success is the ability to go from failure to failure without losing your enthusiasm.  – Sir Winston Churchill',
'Success seems to be connected with action. Successful people keep moving. They make mistakes but don’t quit.  – Conrad Hilton',
'Attitudes are contagious. Make yours worth catching.  – Unknown',
'Do not let what you cannot do interfere with what you can do.  – John Wooden',
'There are only two rules for being successful. One, figure out exactly what you want to do, and two, do it.  – Mario Cuomo',
'Sooner or later, those who win are those who think they can.  – Richard Bach',
'Vision doesn’t usually come as a lightening bolt. Rather it comes as a slow crystallization of life challenges that we one day recognize as a beautiful diamond with great value to ourselves and others.  – Dr. Michael Norwood',
'Success is a state of mind. If you want success, start thinking of yourself as a success.  – Dr. Joyce Brothers',
'Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.  – Samuel Beckett',
'Flops are a part of life’s menu and I’ve never been a girl to miss out on any of the courses.  – Rosalind Russell',
'Cause Change & Lead.  Accept Change & Survive.  Resist Change & Die.  – Ray Norda, Chairman, Novell',
'Winners lose much more often than losers. So if you keep losing but you’re still trying, keep it up! You’re right on track.  – Matthew Keith Groves',
'An idea can turn to dust or magic, depending on the talent that rubs against it.  – Bill Bernbach',
'An obstacle is often a stepping stone.  – Prescott',
'Life is “trying things to see if they work” Ray Bradbury',
'If you worry about yesterday’s failures, then today’s successes will be few.  Anonymous',
'Life is 10% what happens to us and 90% how we react to it.  Dennis P. Kimbro',
'We are all inventors, each sailing out on a voyage of discovery, guided each by a private chart, of which there is no duplicate. The world is all gates, all opportunities.  Ralph Waldo Emerson',
'Knowing is not enough; we must apply. Willing is not enough; we must do.  Johann Wolfgang von Goethe',
'In matters of style, swim with the current; in matters of principle, stand like a rock.  Thomas Jefferson',
'I think and think for months and years. Ninety-nine times, the conclusion is false. The hundredth time I am right.  Albert Einstein',
'Where the willingness is great, the difficulties cannot be great.  Machiavelli.',
'Strength does not come from physical capacity. It comes from an indomitable will.  Mahatma Gandhi',
'You are what you think about all day long.  — Dr. Robert Schuller',
'What you do speaks so loudly that I cannot hear what you say — Ralph Waldo Emerson',
'Success is not to be measured by the position someone has reached in life, but the obstacles he has overcome while trying to succeed.  - Booker T. Washington',
'“Talent is formed in solitude, character in the bustle of the world.” – Johann Wolfgang von Goethe',
'To avoid criticism do nothing, say nothing, be nothing.  – Elbert Hubbard',
'If you want to make your dreams come true, the first thing you have to do is wake up.  – J.M. Power',
'By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day – Robert Frost',
'I’ve learned that no matter what happens, or how bad it seems today, life does go on, and it will be better tomorrow. – Maya Angelou',
'The art of being wise is the art of knowing what to overlook.  – William James',
'When I hear somebody sigh, ‘Life is hard,’ I am always tempted to ask, ‘Compared to what? – Sydney Harris',
'Don’t let life discourage you; everyone who got where he is had to begin where he was.  – Richard L. Evans',
'In three words I can sum up everything I’ve learned about life: It goes on.  – Robert Frost',
'You gain strength, courage and confidence by every experience in which you stop to look fear in the face.  – Eleanor Roosevelt',
'Sometimes even to live is an act of courage.  – Seneca',
'Do first things first, and second things not at all.  – Peter Drucker.',
'The only people who find what they are looking for in life are the fault finders.  – Foster’s Law',
'Defeat is not bitter unless you swallow it.  – Joe Clark',
'I am an optimist. It does not seem too much use being anything else.  – Winston Churchill',
'Positive anything is better than negative thinking.  -Â Elbert Hubbard',
'People seem not to see that their opinion of the world is also a confession of character.  -Â Ralph Waldo Emerson',
'Those who wish to sing, always find a song.  -Â Swedish Proverb',
'If you’re going through hell, keep going.  -Â Winston Churchill',
'The sun shines and warms and lights us and we have no curiosity to know why this is so; but we ask the reason of all evil, of pain, and hunger, and mosquitoes and silly people.  -Â Ralph Waldo Emerson',
'Life is a shipwreck but we must not forget to sing in the lifeboats.  -Â Voltaire',
'Enduring habits I hate…. Yes, at the very bottom of my soul I feel grateful to all my misery and bouts of sickness and everything about me that is imperfect, because this sort of thing leaves me with a hundred backdoors through which I can escape from enduring habits.  – Friedrich Nietzsche,  The Gay Science, 1882',
'There is no education like adversity.  – Disraeli',
'He who has a why to live can bear almost any how.  – Friedrich Nietzsche',
'Adversity introduces a man to himself.  – Author Unknown',
'The secret to life is meaningless unless you discover it yourself.  – W. Somerset Maugham',
'Have the passion, take the action & magic will happen.  – Bar Rafaeli',
'If you’ve got it. use it. If you don’t got it, then get it!  – Reader submitted',
'Son, if you don’t have time to do it right, when will you have time to redo it?  – Reader’s grandfather said this, and I LOVE IT',
'Faith held solely is the begining of action.  – Reader submitted',
'Positivity is all about overlooking the negative fact.  – Reader submitted',
'Life is all about up and doing.  – Reader submitted',
'You will never get lessons on swimming from a drowning man!  – Reader submitted',
'Life is not about ALL the wrong moves you made, Life is about the one right move that made ALL the difference.  – James Lockhart',
'Be humble enough to admit you’re not perfect, but determined enough to strive to be perfect.  – Babsie Burke (reader)',
'If you can’t sleep do not count the sheep, worship the Shepherd.  – Babsie Burke (reader)',
'Life is a journey, its not a race. Walk through it.  – Reader submitted',
'Everything happens for a reason, you only need to keep on editing your attitude and gratitude so as to sail through.  – Reader submitted',
'The measure of who we are is what we do with what we have.  – Reader submitted (I really like this one, thanks Sandiso)',
'If you want to achieve greatness stop asking for permission. ~Anonymous',
'Things work out best for those who make the best of how things work out. ~John Wooden',
'To live a creative life, we must lose our fear of being wrong. ~Anonymous',
'If you are not willing to risk the usual you will have to settle for the ordinary. ~Jim Rohn',
'Trust because you are willing to accept the risk, not because it’s safe or certain. ~Anonymous',
'Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. ~Swami Vivekananda',
'All our dreams can come true if we have the courage to pursue them. ~Walt Disney',
'Good things come to people who wait, but better things come to those who go out and get them. ~Anonymous',
'If you do what you always did, you will get what you always got. ~Anonymous',
'Success is walking from failure to failure with no loss of enthusiasm. ~Winston Churchill',
'Just when the caterpillar thought the world was ending, he turned into a butterfly. ~Proverb',
'Successful entrepreneurs are givers and not takers of positive energy. ~Anonymous',
'Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. ~Vaibhav Shah',
'Opportunities don’t happen, you create them. ~Chris Grosser',
'Try not to become a person of success, but rather try to become a person of value. ~Albert Einstein',
'Great minds discuss ideas; average minds discuss events; small minds discuss people. ~Eleanor Roosevelt',
'I have not failed. I’ve just found 10,000 ways that won’t work. ~Thomas A. Edison',
'If you don’t value your time, neither will others. Stop giving away your time and talents- start charging for it. ~Kim Garst',
'A successful man is one who can lay a firm foundation with the bricks others have thrown at him. ~David Brinkley',
'No one can make you feel inferior without your consent. ~Eleanor Roosevelt',
'The whole secret of a successful life is to find out what is one’s destiny to do, and then do it. ~Henry Ford',
'If you’re going through hell keep going. ~Winston Churchill',
'The ones who are crazy enough to think they can change the world, are the ones that do. ~Anonymous',
'Don’t raise your voice, improve your argument. ~Anonymous',
'What seems to us as bitter trials are often blessings in disguise.~ Oscar Wilde',
'The meaning of life is to find your gift. The purpose of life is to give it away. ~Anonymous',
'The distance between insanity and genius is measured only by success. ~Bruce Feirstein',
'When you stop chasing the wrong things you give the right things a chance to catch you. ~Lolly Daskal',
'Don’t be afraid to give up the good to go for the great. ~John D. Rockefeller',
'No masterpiece was ever created by a lazy artist.~ Anonymous',
'Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. ~Nathaniel Hawthorne',
'If you can’t explain it simply, you don’t understand it well enough. ~Albert Einstein',
'Blessed are those who can give without remembering and take without forgetting. ~Anonymous',
'Do one thing every day that scares you. ~Anonymous',
'What’s the point of being alive if you don’t at least try to do something remarkable. ~Anonymous',
'Life is not about finding yourself. Life is about creating yourself. ~Lolly Daskal',
'Nothing in the world is more common than unsuccessful people with talent. ~Anonymous',
'Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. ~Anonymous',
'Your problem isn’t the problem. Your reaction is the problem. ~Anonymous',
'You can do anything, but not everything. ~Anonymous',
'Innovation distinguishes between a leader and a follower. ~Steve Jobs',
'There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. ~Ray Goforth',
'Thinking should become your capital asset, no matter whatever ups and downs you come across in your life. ~Dr. APJ Kalam',
'I find that the harder I work, the more luck I seem to have. ~Thomas Jefferson',
'The starting point of all achievement is desire. ~Napolean Hill',
'Success is the sum of small efforts, repeated day-in and day-out. ~Robert Collier',
'If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. ~Thomas J. Watson',
'All progress takes place outside the comfort zone. ~Michael John Bobak',
'You may only succeed if you desire succeeding; you may only fail if you do not mind failing. ~Philippos',
'Courage is resistance to fear, mastery of fear - not absense of fear. ~Mark Twain',
'Only put off until tomorrow what you are willing to die having left undone. ~Pablo Picasso',
'People often say that motivation doesn’t last. Well, neither does bathing - that’s why we recommend it daily. ~Zig Ziglar',
'We become what we think about most of the time, and that’s the strangest secret. ~Earl Nightingale',
'The only place where success comes before work is in the dictionary. ~Vidal Sassoon',
'The best reason to start an organization is to make meaning; to create a product or service to make the world a better place. ~Guy Kawasaki',
'I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. ~Martha Stewart',
'It’s not what you look at that matters, it’s what you see. ~Anonymous',
'The road to success and the road to failure are almost exactly the same. ~Colin R. Davis',
'The function of leadership is to produce more leaders, not more followers. ~Ralph Nader',
'Success is liking yourself, liking what you do, and liking how you do it. ~Maya Angelou',
'As we look ahead into the next century, leaders will be those who empower others. ~Bill Gates',
'A real entrepreneur is somebody who has no safety net underneath them. ~Henry Kravis',
'The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. ~Mark Caine',
'People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. ~Tony Robbins',
'When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. ~Audre Lorde',
'Whenever you find yourself on the side of the majority, it is time to pause and reflect. ~Mark Twain',
'The successful warrior is the average man, with laser-like focus. ~Bruce Lee',
'Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. ~Swami Vivekananda',
'Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. ~Dale Carnegie',
'If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much. ~ Jim Rohn',
'If you genuinely want something, don’t wait for it — teach yourself to be impatient. ~Gurbaksh Chahal',
'Don’t let the fear of losing be greater than the excitement of winning. ~Robert Kiyosaki',
'If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! ~T. Harv Eker',
'You can’t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life. ~Steve Jobs',
'Successful people do what unsuccessful people are not willing to doDon’t wish it were easier, wish you were better. ~Jim Rohn',
'The number one reason people fail in life is because they listen to their friends, family, and neighbors. ~Napoleon Hill',
'The reason most people never reach their goals is that they don’t define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them. ~Denis Watiley',
'In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. ~Jane Smiley',
'Success does not consist in never making mistakes but in never making the same one a second time. ~George Bernard Shaw',
'I don’t want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. ~Diane Ackerman',
'You must expect great things of yourself before you can do them. ~Michael Jordan',
'Motivation is what gets you started. Habit is what keeps you going. ~Jim Ryun',
'People rarely succeed unless they have fun in what they are doing. ~Dale Carnegie',
'There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. ~Ella Wheeler Wilcox',
'Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter. ~Francis Chan',
'You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. ~George Lorimer',
'To be successful you must accept all challenges that come your way. You can’t just accept the ones you like. ~Mike Gafka',
'Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others. ~ John C. Maxwell',
'Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice. ~Wayne Dyer',
'To accomplish great things, we must not only act, but also dream, not only plan, but also believe. ~Anatole France',
'Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all. ~Dale Carnegie',
'You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. ~Booker T. Washington',
'Real difficulties can be overcome; it is only the imaginary ones that are unconquerable. ~Theodore N. Vail',
'It is better to fail in originality than to succeed in imitation. ~Herman Melville',
'Fortune sides with him who dares. ~Virgil',
'Little minds are tamed and subdued by misfortune; but great minds rise above it. ~Washington Irving',
'Failure is the condiment that gives success its flavor. ~Truman Capote',
'Don’t let what you cannot do interfere with what you can do. ~John R. Wooden',
'You may have to fight a battle more than once to win it. ~Margaret Thatcher',
'A man can be as great as he wants to be. If you believe in yourself and have the courage, the determination, the dedication, the competitive drive and if you are willing to sacrifice the little things in life and pay the price for the things that are worthwhile, it can be done. ~Vince Lombardi',
'Like a fish, one should look for a hole in the net.  ~Samoan Proverb',
'Persevere like a bird in the wind.  ~Samoan Proverb',
'Life is like this: sometimes sun, sometimes rain.  ~Fijian Proverb',
'All knowledge is not taught in one school.  ~ Hawaiian Proverb'
'Wonderful people come in different shapes and sizes.',
'Beauty is how you feel on the inside.',
"Take care of your body.  It's the only place you have to live.  ~Jim Rohn",
'Of all things you wear, your expression is the most important.',
'Beauty captures your attention but personality captures your heart.',
"I've never seen a smiling face that was not beautiful.",
'Happiness is not a station you arrive at, but a manner of traveling.  ~Margaret B. Runbeck',
"Life isn't about finding yourself.  Life is about creating yourself.  ~George Bernard Shaw",
'Failure is success if we learn from it.  ~Malcolm S. Forbes',
'But the real secret to total gorgeousness is to believe in yourself, have self confidence, and try to be secure in your decisions and thoughts.  ~Kirsten Dunst',
'Everything has beauty, but not everyone sees it.  ~Confucius',
"It's not what you look like, that makes you who you are.  It's what you do, that makes you who you are.",
'One can build a better world by using our talents.',
'Beauty is not in the face; beauty is a light in the heart.  ~Kahlil Gibran',
"That which is striking and be autiful is not always good, but that which is good is always beautiful.  ~Ninon de L'Enclos",
'Energy and persistence conquer all things.  -Benjamin Franklin',
'An intelligent plan is the first step to success. The man who plans knows where he is going, knows what progress he is making and has a pretty good idea when he will arrive. Planning is the open road to your destination.  -Basil S. Walsh',
'Whoever wants to reach a distant goal must take many small steps.  -Helmut Schmidt',
'Discipline is remembering what you want.  -David Campbell',
'A man who is a master of patience is a master of everything else.  -George Savile',
'Honesty is the best policy.  -Benjamin Franklin',
'The secret of success is constancy of purpose.  -Benjamin Disraeli',
'People with goals succeed because they know where they are going.  -Earl Nightingale',
'Your work is to discover your work, and then with all your heart, to give yourself to it.  -Buddha',
'To win, you have to have the talent and desire. But desire is first.  -Sam Snead',
'No one knows what he can do till he tries.  -Syrus',
'Education is the best provision for the journey to old age.  -Aristotle',
'Success is the ability to go from one failure to another with no loss of enthusiasm.  -Sir Winston Churchill',
'The best way to make your dreams come true is to wake up.  -Paul Valery',
'If you can dream it, you can do it.  -Walt Disney',
'Never put off till tomorrow what you can do today.  -Benjamin Franklin',
'Wherever you go, go with all your heart.  -Confucius',
'To be prepared is half the victory.  -Miguel de Cervantes',
'If you want a thing done well, do it yourself.  -Napoleon Bonaparte',
'An investment in knowledge pays the best interest.  -Benjamin Franklin',
'One man with courage makes a majority.  -Andrew Jackson',
'It concerns us to know the purposes we seek in life, for then, like archers aiming at a definite mark, we shall be more likely to attain what we want.  -Aristotle',
'Raise your hopes and expectations high enough, and you shall touch wings with the divine.  -Celia Mora',
'You are the product of your own brainstorm.  -Rosemary Konner Steinbaum',
'The man who has no imagination has no wings.  -Muhammad Ali',
"One of the things I learned the hard way was that it doesn't pay to get discouraged. Keeping busy and making optimism a way of life can restore your faith in yourself.  -Lucille Ball",
'You gain strength, courage and confidence by every experience in which you really stop to look fear in the face. You are able to say to yourself, I lived through this horror. I can take the next thing that comes along.  -Eleanor Roosevelt',
'The measure of a man is the way he bears up under misfortune.  -Plutarch',
'Just trust yourself, then you will know how to live.  -Johann Wolfgang von Goethe',
'Fortune favors the brave.  -Terrence',
"I have not failed. I've just found 10,000 ways that don't work.  -Thomas Edison",
'I not only use all the brains that I have, but all that I can borrow.  -Woodrow Wilson',
'If the only tool you have is a hammer, every problem looks like a nail.  -Abraham Maslow',
'Do not follow where the path may lead. Go, instead, where there is no path and leave a trail.  -Ralph Waldo Emerson',
'Anger is a wind which blows out the lamp of the mind.  -Robert Ingersoll',
"When I do good, I feel good. When I do bad, I feel bad. That's my religion.  -Abraham Lincoln",
'No pressure, no diamonds.  -Thomas Carlyle',
"I'm a great believer in luck and I find the harder I work, the more I have of it.  -Thomas Jefferson",
"It's kind of fun to do the impossible.  -Walt Disney",
'An ant on the move does more than a dozing ox.  -Lao Tzu',
'There is no failure except in no longer trying.  -Elbert Hubbard',
'Formal education will make you a living. Self-education will make you a fortune.  -Jim Rohn',
'I walk slowly; but I never walk backward.  -Abraham Lincoln',
'The great use of life is to spend it on something that will outlast it.  -William James',
"There is no giant step that does it. It's a lot of little steps.  -Peter A. Cohen",
'We must wake ourselves up! Or somebody else will take our place, and bear our cross, and thereby rob us of our crown.  -William Booth',
'In the time of darkest defeat, victory may be nearest.  -William McKinley',
'It is not death that a man should fear, but he should fear never beginning to live.  -Marcus Aurelius',
'Action may not always bring happiness; but there is no happiness without action.  -Benjamin Franklin',
'Discipline is the bridge between goals and accomplishment.  -Jim Rohn',
'People may doubt what you say, but they will believe what you do.  -Lewis Cass',
'Give me six hours to chop down a tree and I will spend the first four sharpening the axe.  -Abraham Lincoln',
'For myself I am an optimist – it does not seem to be much use being anything else.  -Sir Winston Churchill',
'All things are difficult before they are easy.  -Thomas Fuller',
'We are what we repeatedly do. Excellence is therefore not an act but a habit.  -Aristotle',
'Great spirits have always encountered violent opposition from mediocre minds.  -Albert Einstein',
'Success is how high you bounce when you hit bottom.  -George Smith Patton, Jr.',
"It is necessary for us to learn from other's mistakes. You will not live long enough to make them all yourself.  -Hyman George Rickover",
'I want to live my life so that my nights are not full of regrets.  -D. H. Lawrence',
'The world makes way for the man who knows where he is going.  -Ralph Waldo Emerson',
'The principle goal of education is to create men who are capable of doing new things, not simply of repeating what other generations have done – men who are creative, and inventive.  -Jean Piaget',
'We must be the change we wish to see in the world.  -Mahatma Gandhi',
'Things may come to those who wait, but only the things left by those who hustle.  -Abraham Lincoln',
'Success depends upon previous preparation, and without such preparation there is sure to be failure.  -Confucius',
'Nothing in the world can take the place of persistence. Talent will not; nothing is more common than unsuccessful men with talent. Genius will not; unrewarded genius is almost a proverb. Education will not; the world is full of educated derelicts.  Persistence and determination alone are omnipotent. The slogan  ́Press on ́ has solved and always will solve the problems of the human race.  -Calvin Coolidge',
'A jug fills drop by drop.  -Buddha',
'Either write something worth reading or do something worth writing.  -Benjamin Franklin',
'Pessimism leads to weakness, optimism to power.  -Wiliam James',
'He that respects himself is safe from others. He wears a coat of mail that none can pierce.  -Henry Wadsworth Longfellow',
'Know or listen to those who know.  -Baltasar Gracian',
'In life, as in chess, forethought wins.  -Charles Buxton',
'The winds and the waves are always on the side of the ablest navigators.  -Edward Gibbon',
'Nothing gives one person so much advantage over another as to remain always cool and unruffled under all circumstances.  -Thomas Jefferson',
'To do a common thing uncommonly well brings success.  -Henry J. Heinz',
"I've got a great ambition to die of exhaustion rather than boredom.  -Thomas Carlyle",
'When angry count to ten before you speak. If very angry, count to one hundred.  -Thomas Jefferson',
'To educate a man is to unfit him to be a slave.  -Fredrick Douglas',
'Never mistake motion for action.  -Ernest Hemingway',
'I am always doing that which I can not do; in order that I may learn how to do it.  -Pablo Picasso',
'All glory comes from daring to begin.  -Eugene F. Ware',
"If your ship doesn't come in, swim out to it.  -Jonathan Winters",
'Just as iron rusts from disuse, even so does inaction spoil the intellect.  -Leonardo Da Vinci',
"Don't believe that winning is everything. It's more important to stand for something.  If you don't stand for something, what do you win?  -Lane Kirkland",
'If you risk nothing, then you risk everything.  -Geena Davis',
"Life is always walking up to us and saying, 'Come on in, the living's fine', and what do we do? Back off and take its picture.  -Russell Baker",
'You have to be careful about being too careful.  -Beryl Pfizer',
'Imagination is more important than knowledge.  -Albert Einstein',
'A good conscience is a continual Christmas.  -Benjamin Franklin',
'The strength of a nation derives from the integrity of the home.  -Confucius',
'Ideas are like rabbits. You get a couple and learn how to handle them, and pretty soon you have a dozen.  -John Steinbeck',
'A public-opinion poll is no substitute for thought.  -Warren Buffett',
'Success covers a multitude of blunders.  -Bernard Shaw',
"The cynic says, 'One man can't do anything.' I say, 'Only one man can do anything.' One man interacting creatively with others can move the world.  -John W. Gardner",
'Life is a great big canvas, and you should throw all the paint on it you can.  -Danny Kaye',
"Life is like a dog-sled team. If you ain't the lead dog, the scenery never changes.  -Lewis Grizzard",
'Life is my college. May I graduate well, and earn some honors!  -Louisa May Alcott',
"It's not what happens to you, but how you react to it that matters.  -Epictetus",
'Success usually comes to those who are too busy to be looking for it.  -Henry David Thoreau',
'Do the duty which lies nearer to you, the second duty will then become clearer.  -Thomas Carlyle',
'To be idle is a short road to death and to be dilligent is a way of life; foolish people are idle, wise people are dilligent.  -Buddha',
'Success usually comes to those who are too busy to be looking for it. Henry David Thoreau',
'If you are not willing to risk the usual, you will have to settle for the ordinary. Jim Rohn',
'Take up one idea. Make that one idea your life-think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. Swami Vivekananda',
'If you are willing to do more than you are paid to do, eventually you will be paid to do more than you do. Anonymous',
'Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them. Vaibhav Shah',
'Try not to become a person of success, but rather try to become a person of value. Albert Einstein',
'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. Charles Darwin',
'Great minds discuss ideas; average minds discuss events; small minds discuss people. Eleanor Roosevelt',
'No one can make you feel inferior without your consent. Eleanor Roosevelt',
'The distance between insanity and genius is measured only by success. Bruce Feirstein',
"Don't be afraid to give up the good to go for the great. John D. Rockefeller",
"If you can't explain it simply, you don't understand it well enough. Albert Einstein",
'There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. Ray Goforth',
'Success is the sum of small efforts, repeated day in and day out. Robert Collier',
'Courage is resistance to fear, mastery of fear -- not absence of fear. Mark Twain',
'Only put off until tomorrow what you are willing to die having left undone. Pablo Picasso',
"Twenty years from now, you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover. Mark Twain",
'The successful warrior is the average man, with laserlike focus. Bruce Lee',
"Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. Jim Rohn",
'The No. 1 reason people fail in life is because they listen to their friends, family, and neighbors. Napoleon Hill',
'You may have to fight a battle more than once to win it. Margaret Thatcher',
"Many of life's failures are people who did not realize how close they were to success when they gave up. Thomas A. Edison",
'What would you attempt to do if you knew you would not fail? Robert Schuller',
'Always bear in mind that your own resolution to success is more important than any other one thing. Abraham Lincoln',
'Successful and unsuccessful people do not vary greatly in their abilities. They vary in their desires to reach their potential. John Maxwell',
"I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. Maya Angelou",
"Much of the stress that people feel doesn't come from having too much to do. It comes from not finishing what they've started. David Allen",
'Focus on the journey, not the destination. Joy is found not in finishing an activity but in doing it. Greg Anderson',
'You never regret being kind. Nicole Shepherd',
"Success at the highest level comes down to one question: Can you decide that your happiness can come from someone else's success? Bill Walton",
"Do what you have always done and you'll get what you have always got. Sue Knight",
'Think of what you have rather than of what you lack. Of the things you have, select the best and then reflect how eagerly you would have sought them if you did not have them. Marcus Aurelius',
'Happiness is where we find it, but very rarely where we seek it. J. Petit Senn',
'To be content means that you realize you contain what you seek. Alan Cohen',
'Expecting life to treat you well because you are a good person is like expecting an angry bull not to charge because you are a vegetarian. Shari R. Barr',
"View your life from your funeral: Looking back at your life experiences, what have you accomplished? What would you have wanted to accomplish but didn't? What were the happy moments? What were the sad? What would you do again, and what wouldn't you do? Victor Frankl",
'Boredom is the feeling that everything is a waste of time...serenity, that nothing is. Thomas Szasz',
'To handle yourself, use your head; to handle others, use your heart. Eleanor Roosevelt',
'The mediocre teacher tells. The good teacher explains. The superior teacher demonstrates. The great teacher inspires. William Arthur Ward',
'Keep your fears to yourself, but share your courage with others. Robert Louis Stevenson',
'The greatest leader is not necessarily the one who does the greatest things. He is the one that gets people to do the greatest things. Ronald Reagan',
"Power isn't control at all-power is strength, and giving that strength to others. A leader isn't someone who forces others to make him stronger; a leader is someone willing to give his strength to others that they may have the strength to stand on their own. Beth Revis",
"Don't tell people how to do things; tell them what to do and let them surprise you with their results. George S. Patton Jr.",
'Leadership is the art of getting someone else to do something you want done because he wants to do it. Dwight D. Eisenhower',
'Victory has a hundred fathers and defeat is an orphan. John F. Kennedy',
'Management is doing things right; leadership is doing the right things. Peter F. Drucker',
'Example is not the main thing in influencing others. It is the only thing. Albert Schweitzer',
'Leaders must be close enough to relate to others, but far enough ahead to motivate them. John C. Maxwell',
'The mark of a great man is one who knows when to set aside the important things in order to accomplish the vital ones. Brandon Sanderson',
'Leadership is not about titles, positions, or flowcharts. It is about one life influencing another. John C. Maxwell',
"You have to be burning with an idea, or a problem, or a wrong that you want to right. If you're not passionate enough from the start, you'll never stick it out. Steve Jobs",
'A leader ... is like a shepherd. He stays behind the flock, letting the most nimble go out ahead, whereupon the others follow, not realizing that all along they are being directed from behind. Nelson Mandela',
'Being responsible sometimes means pissing people off. Colin Powell',
'Do you know that one of the great problems of our age is that we are governed by people who care more about feelings than they do about thoughts and ideas. Margaret Thatcher',
'A leader is a dealer in hope. Napoleon',
'The best executive is the one who has sense enough to pick good men to do what he wants done, and self-restraint to keep from meddling with them while they do it. Theodore Roosevelt',
'If you would convince a man that he does wrong, do right. But do not care to convince him. Men will believe what they see. Let them see. Henry David Thoreau',
'I cannot trust a man to control others who cannot control himself. Robert E. Lee',
"Consensus: the process of abandoning all beliefs, principles, values, and policies in search of something in which no one believes, but to which no one objects; the process of avoiding the very issues that have to be solved, merely because you cannot get agreement on the way ahead. What great cause would have been fought and won under the banner: 'I stand for consensus?' Margaret Thatcher",
"A leader takes people where they want to go. A great leader takes people where they don't necessarily want to go but ought to be. Rosalynn Carter",
'There is a difference between being a leader and being a boss. Both are based on authority. A boss demands blind obedience; a leader earns his authority through understanding and trust. Klaus Balkenhol',
'You get in life what you have the courage to ask for. Nancy D. Solomon',
'In the end, it is important to remember that we cannot become what we need to be by remaining what we are. Max De Pree',
"A leader isn't someone who forces others to make him stronger; a leader is someone willing to give his strength to others so that they may have the strength to stand on their own. Beth Revis",
"Always remember, Son, the best boss is the one who bosses the least. Whether it's cattle, or horses, or men, the least government is the best government. Ralph Moody",
'If you really want the key to success, start by doing the opposite of what everyone else is doing. Brad Szollose',
"Give as few orders as possible, his father had told him once long ago. Once you've given orders on a subject, you must always give orders on that subject. Frank Herbert (from Dune)",
'The art of leadership is saying no, not yes. It is very easy to say yes. Tony Blair',
'Wisdom equals knowledge plus courage. You have to not only know what to do and when to do it, but you have to also be brave enough to follow through. Jarod Kintz',
"In a battle between two ideas, the best one doesn't necessarily win. No, the idea that wins is the one with the most fearless heretic behind it. Seth Godin",
"If you want to build a ship, don't drum up the men to gather wood, divide the work, and give orders. Instead, teach them to yearn for the vast and endless sea. Antoine de Saint-Exupery",
'Remember, teamwork begins by building trust. And the only way to do that is to overcome our need for invulnerability. Patrick Lencioni',
'Leadership is an action, not a position. Donald McGannon',
'Surround yourself with great people; delegate authority; get out of the way. Ronald Reagan',
'I cannot give you a formula for success, but I can give you the formula for failure, which is: Try to please everybody. Herbert Bayard Swope',
'Show me the man you honor and I will know what kind of man you are. Thomas John Carlisle',
'A man always has two reasons for doing anything: a good reason and the real reason. J.P. Morgan',
'If you spend your life trying to be good at everything, you will never be great at anything. Tom Rath',
'Average leaders raise the bar on themselves; good leaders raise the bar for others; great leaders inspire others to raise their own bar. Orrin Woodward',
"Don't blow off another's candle for it won't make yours shine brighter. Jaachynma N.E. Agu",
'Whenever you see a successful business, someone once made a courageous decision. Peter F. Drucker',
'When you put together deep knowledge about a subject that intensely matters to you, charisma happens. You gain courage to share your passion, and when you do that, folks follow. Jerry Porras',
'People buy into the leader before they buy into the vision. John Maxwell',
'A good leader is a person who takes a little more than his share of the blame and a little less than his share of the credit. John Maxwell',
'A good plan violently executed now is better than a perfect plan executed next week. George Patton',
'Feeling gratitude and not expressing it is like wrapping a present and not giving it. William Arthur Ward',
"Silent gratitude isn't very much to anyone. Gertrude Stein",
'The only people with whom you should try to get even are those who have helped you. John E. Southard',
'Keep your eyes open and try to catch people in your company doing something right, then praise them for it. Tom Hopkins',
"You wouldn't worry so much about what others think of you if you realized how seldom they do. Eleanor Roosevelt",
"Low self-confidence isn't a life sentence. Self-confidence can be learned, practiced, and mastered-just like any other skill. Once you master it, everything in your life will change for the better. Barrie Davenport",
'Shyness has a strange element of narcissism, a belief that how we look, how we perform, is truly important to other people. Andre Dubus',
'Do it or not. There is no try. Yoda',
'Rarely have I seen a situation where doing less than the other guy is a good strategy. Jimmy Spithill',
'You may have to fight a battle more than once to win it. Margaret Thatcher',
'The best revenge is massive success. Frank Sinatra',
"The question isn't who is going to let me; it's who is going to stop me. Ayn Rand",
'The only way to do great work is to love what you do. Steve Jobs'
]

i = randint(0, len(quotes) - 1)
print(quotes[i])
